<x-app-layout>
  <x-custom.list
    :items="$items"
    :columns="$columns"
    :enableSearch="true"
    :filter="true"
    :searchBy="$searchBy" 
    :searchRoutes="$searchRoutes"
  />
</x-app-layout>